name: Continuous Integration

on:
  pull_request:
    branches: [ master ]

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install packages
        run: sudo gem install mdl
      - name: Lint markdown files
        run: mdl . -r ~MD036,~MD024,~MD004,~MD029
      - run: pip install -r requirements.txt
      - run: mkdocs build --strict
      - run: npm install
      - run: node .github/manual_lint.js
      - name: Comment
        if: always()
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: '只有通过自动化检查的合并请求才会被人工审批，请确保此 Pull Request 能够通过自动化检查！'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: quipper/comment-failure-action@v0.1.1
        # Suppress 036 Emphasis used instead of a header
        # Suppress 024 Multiple headers with the same content
